In [129]:
import cv2
import numpy as np 
import os
from PIL import Image
import shutil

In [176]:
os.getcwd()

'C:\\Users\\User\\Documents\\PythonProject\\dataset'

In [175]:
os.chdir('.\dataset')

In [140]:
os.chdir('dataset')
os.getcwd()

'C:\\Users\\User\\Documents\\PythonProject\\dataset'

In [141]:
os.listdir()


['0',
 '1',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '2',
 '20',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9']

In [142]:
#Изменение размера/ Подгонка размера под 40х40
def transform_scale(img):
    dim = (40, 40)
    img = cv2.resize(img, dim, interpolation = cv2.INTER_AREA)
    return img

#Открытие картинки 
def openPicture(name):
    image = cv2.imread(name)
    return image

#Показ картинки
def showPicture(name):
    cv2.imshow("Image", name)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

def transform_gray(img):
    gray_img = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    ret, threshold_img = cv2.threshold(gray_img, 127, 255, 0)
    return threshold_img


In [143]:
#объединение изображений в одну переменную 
x = []
y = []

#os.listdir('.')
for i in os.listdir('.'):
    os.chdir(i)
#     for file in os.listdir('.'):
#         if file=='output':
#             os.rename('output', 'outputlast')
#     os.mkdir('output')
    for file in os.listdir('.'):
        if file=='output':
            continue
        # image_1 = transform_gray(image)
        image = openPicture(file)
        gray_img = transform_gray(image)
        image_2 = transform_scale(gray_img)  ##        image_2 = transform_scale(image)  было так
        dim = (40, 40)
        image_3 = cv2.resize(image_2, dim, interpolation = cv2.INTER_AREA)
        # showPicture(image_2)
#         os.chdir('output')
#         bb=str(file)
#         cv2.imwrite(bb, image_3)
#         os.chdir('..')
        
        x.append(image_3) #Массив сжатых картинок 
        y.append(int(i)) #Массив папок-классов
        
    os.chdir('..')
    


In [11]:
image_2.shape

(40, 40)

In [ ]:
os.getcwd()
# os.listdir()
os.chdir('0')
print(os.listdir())
image=cv2.imread('0.bmp')
os.chdir('..')

In [ ]:
image.shape

In [ ]:
image = cv2.imread('0.bmp')
image1 = transform_gray(image)
# print(image1.shape)
image2 = np.resize(image1,(40, 40))
image2.shape


In [144]:
x = np.array(x).astype('float32')
x /= 255
x = np.array(x).astype('float32')

y = np.array(y).astype('float32')

x.shape


(14357, 40, 40)

In [145]:
x = x.reshape(-1, 40, 40, 1) #?
x.shape

(14357, 40, 40, 1)

In [146]:
from sklearn.model_selection import train_test_split

from keras.models import Sequential
from keras.utils import np_utils
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras.layers.normalization import BatchNormalization

In [147]:
model = Sequential()

model.add(Conv2D(input_shape = (40, 40, 1), filters = 32, kernel_size=(3, 3), activation='relu'))
model.add(BatchNormalization())
model.add(MaxPooling2D((2, 2)))

model.add(Conv2D(filters = 32, kernel_size=(3, 3), activation='relu'))
model.add(BatchNormalization())
model.add(MaxPooling2D())


model.add(Conv2D(filters = 64, kernel_size=(3, 3), activation='relu'))
model.add(BatchNormalization())
#model.add(MaxPooling2D())

model.add(Conv2D(filters = 128, kernel_size=(3, 3), activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(rate = 0.2))
model.add(MaxPooling2D())



model.add(Flatten())
model.add(Dense(128, activation='relu'))
#model.add(Dropout(rate = 0.2))
model.add(Dense(21, activation='softmax'))


In [148]:
import keras
model.compile(loss = 'categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

In [149]:
y1 = keras.utils.to_categorical(y,21)

In [150]:
x_train, x_val, y_train, y_val = train_test_split(x, y1, test_size=0.15, random_state=13)

In [151]:
history = model.fit(x_train, y_train, epochs=2, batch_size=50)

Epoch 1/2
12203/12203 [==============================] - 32s 3ms/step - loss: 0.1338 - accuracy: 0.9672
Epoch 2/2
12203/12203 [==============================] - 30s 2ms/step - loss: 0.0134 - accuracy: 0.9967


In [152]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_5 (Conv2D)            (None, 38, 38, 32)        320       
_________________________________________________________________
batch_normalization_5 (Batch (None, 38, 38, 32)        128       
_________________________________________________________________
max_pooling2d_4 (MaxPooling2 (None, 19, 19, 32)        0         
_________________________________________________________________
conv2d_6 (Conv2D)            (None, 17, 17, 32)        9248      
_________________________________________________________________
batch_normalization_6 (Batch (None, 17, 17, 32)        128       
_________________________________________________________________
max_pooling2d_5 (MaxPooling2 (None, 8, 8, 32)          0         
_________________________________________________________________
conv2d_7 (Conv2D)            (None, 6, 6, 64)         

In [179]:
os.listdir()

['0 (2).bmp',
 '0.bmp',
 '1 (2).bmp',
 '1000.bmp',
 '1001.bmp',
 '1002.bmp',
 '1003.bmp',
 '1004.bmp',
 '1005.bmp',
 '1006.bmp',
 '1007.bmp',
 '1008.bmp',
 '1009.bmp',
 '101 (2).bmp',
 '101.bmp',
 '1010.bmp',
 '1011.bmp',
 '1012.bmp',
 '1013.bmp',
 '1014.bmp',
 '1015.bmp',
 '1016.bmp',
 '1019.bmp',
 '102 (2).bmp',
 '102.bmp',
 '1020.bmp',
 '1024.bmp',
 '1025.bmp',
 '1029.bmp',
 '103 (2).bmp',
 '103.bmp',
 '1030.bmp',
 '1031.bmp',
 '1032.bmp',
 '1033.bmp',
 '1034.bmp',
 '1035.bmp',
 '1036.bmp',
 '1037.bmp',
 '1039.bmp',
 '104.bmp',
 '1040.bmp',
 '1043.bmp',
 '1044.bmp',
 '1045.bmp',
 '1047.bmp',
 '1048.bmp',
 '1049.bmp',
 '105 (2).bmp',
 '105.bmp',
 '1050.bmp',
 '1051.bmp',
 '1052.bmp',
 '1053.bmp',
 '1054.bmp',
 '1055.bmp',
 '1056.bmp',
 '1057.bmp',
 '1058.bmp',
 '1059.bmp',
 '106 (2).bmp',
 '106.bmp',
 '1060.bmp',
 '1061.bmp',
 '1062.bmp',
 '1063.bmp',
 '1064.bmp',
 '1065.bmp',
 '1066.bmp',
 '1067.bmp',
 '1069.bmp',
 '1071.bmp',
 '1072.bmp',
 '1075.bmp',
 '1076.bmp',
 '108.bmp',
 '108

In [190]:
os.chdir('test')

In [204]:
os.getcwd()
os.listdir()

['asd', 'flip.png', 'ou', 'test.bmp', 'test2.bmp']

In [205]:
# Открытие собственной картинки и определение символа на ней
# os.getcwd()
# os.chdir('test')
image = openPicture('test2.bmp')
image1 = transform_gray(image)
image2 = transform_scale(image1)
image3 = image2.reshape(-1,40,40,1)


In [195]:
# cv2.imwrite("flip.png", image)

In [196]:
# os.mkdir('asd')

In [206]:
image3.shape

(1, 40, 40, 1)

In [208]:
image4 = np.array(image3).astype('float32')
vector = model.predict_proba(image4)
# vector = vector.astype('')
vector

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 1.]], dtype=float32)

In [209]:
np.max(vector)
num_class = (np.where(vector == np.amax(vector))[1])
num_class

array([20], dtype=int64)

In [210]:
# os.getcwd()
# # os.listdir()
# os.chdir('12')
# print(os.listdir())
# image=cv2.imread('0.bmp')
# os.chdir('..')

In [211]:
#image = openPicture('0.bmp')
image1 = transform_gray(image)
image2 = transform_scale(image1)
image3 = image2.reshape(-1, 40, 40, 1)

In [69]:
image3.shape

(1, 40, 40, 1)

In [45]:
image4 = np.array(image3).astype('float32')

In [61]:
vector = model.predict(image4)
# vector = vector.astype('')
vector


array([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.]], dtype=float32)

In [47]:
np.max(vector)

1.0

In [48]:
num_class = (np.where(vector == np.amax(vector))[1])

In [49]:
num_class

array([0], dtype=int64)

In [50]:
np.__version__

'1.16.4'